site_name: SmartConsole
site_description: The official documentation of SmartConsole.
site_author: Maximilian Schmidt
site_url: https://smartconsole.readthedocs.io

copyright: Copyright &copy; 2018 Maximilian Schmidt

docs_dir: Docs

theme:
  name: readthedocs
  highlightjs: false

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - 
    codehilite:
      linenums: false
  - 
    toc:
      permalink: true
  - meta
  - 
    pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

pages:
  - Documentation:
    - Introduction: index.md
    - Usage Guide: usage.md
  - Reference:
    - The analysis algorithm: references/algorithm.md
    - Configuration: references/configuration.md
    - Annotations: references/annotations.md
    - IO Component: references/output.md
    - Global Options: references/options.md
  - Examples:
    - Overview: examples/overview.md
    - Rudimentary Setup: examples/guide.md